import { Product } from "./types/Product";

export const sampleProducts: Product[]=[
    {
        
        // _id: '8',
        name: 'V-neck Cable Knit Cardigan',
        slug: 'v-neck-cable-knit-cardigan',
        category: 'Women',
        image: './images/product-1.jpg',
        price: 420,
        brand: 'Hiskywin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
        description: 'Polo-neck',
    },
    {
    // _id: '999999999999999999999999',
    name: 'WOOLWORTH  Textured Knit Cardigan',
    slug: 'woolworth-textured-knit-cardigan',
    category: 'Women',
    image: './images/product-2.jpg',
    price: 450,
    brand: 'Hiskywin',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Polo-neck',
    },
    {
    // _id: '10',
    name: 'Longline Cable Knit Jumper',
    slug: 'longline-cable-knit-jumper',
    category: 'Women',
    image: './images/product-3.jpg',
    price: 480,
    brand: 'Hiskywin',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Polo-neck',
    },
    {
    // _id: '11',
    name: 'Poloneck Cable Knit Jumper',
    slug: 'poloneck-cable-knit-jumper',
    category: 'Women',
    image: './images/product-4.jpg',
    price: 500,
    brand: 'Hiskywin',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Polo-neck',
    },
    {
    // _id: '12',
    name: 'Plain Poloneck',
    slug: 'plain-poloneck',
    category: 'Men',
    image: './images/product-5.jpg',
    price: 300,
    brand: 'Hiskywin',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Polo-neck',
    },
    {
    // _id: '13',
    name: 'Cable Knit Poloneck',
    slug: 'cable-knit-poloneck',
    category: 'Men',
    image: './images/product-6.jpg',
    price: 380,
    brand: 'Hiskywin',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Polo-neck',
    },
    {
    // _id: '1',
    name: 'Enjoy Life Forever',
    slug: 'enjoy-life-forever',
    category: 'Men',
    image: './images/enjoy-life-forever.jpg',
    price: 60,
    brand: 'brochure',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '2',
    name: 'Exercise Faith',
    slug: 'exercise-faith',
    category: 'Books',
    image: './images/exercise-faith.jpg',
    price: 100,
    brand: 'brochure',
    rating: 3.5,
    numReviews: 100,
    countInStock: 5,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '3',
    name: 'Friends of peace',
    slug: 'friends-of-peace',
    category: 'Books',
    image: './images/friends-of-peace.jpg',
    price: 160,
    brand: 'brochure',
    rating: 3.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '4',
    name: "Jehovah's united Family",
    slug: 'jehovahs-united-family',
    category: 'Books',
    image: './images/jehovah-united-family.jpg',
    price: 200,
    brand: 'brochure',
    rating: 5,
    numReviews: 10,
    countInStock: 10,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '5',
    name: 'Powerful by Faith',
    slug: 'powerful-by-faith',
    category: 'Books',
    image: './images/powerful-by-faith.jpg',
    price: 200,
    brand: 'brochure',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '6',
    name: 'Pursue Peace',
    slug: 'pursue-peace',
    category: 'Books',
    image: './images/pursue-peace.jpg',
    price: 60,
    brand: 'brochure',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Jehovah Witnesses',
    },
    {
    // _id: '7',
    name: 'Strenghten your Faith',
    slug: 'strenghten-your-faith',
    category: 'Books',
    image: './images/strenghten-your-faith.jpg',
    price: 60,
    brand: 'brochure',
    rating: 4.5,
    numReviews: 10,
    countInStock: 6,
    description: 'Jehovah Witnesses',
    }
]